server.port=8080

spring.security.oauth2.client.registration.file-client.client-id=file-client
spring.security.oauth2.client.registration.file-client.client-secret=secret
spring.security.oauth2.client.registration.file-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.file-client.redirect-uri=http://localhost:8080/login/oauth2/code/file-client
spring.security.oauth2.client.registration.file-client.scope=openid,files.read,files.write

spring.security.oauth2.client.provider.file-client.issuer-uri=http://127.0.0.1:9000